// Mocks generated by Mockito from annotations
// in omni_for_pyload/test/features/settings/viewmodel/settings_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:omni_for_pyload/domain/models/app_settings.dart' as _i2;
import 'package:omni_for_pyload/domain/repositories/i_app_info_repository.dart'
    as _i5;
import 'package:omni_for_pyload/domain/repositories/i_settings_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAppSettings_0 extends _i1.SmartFake implements _i2.AppSettings {
  _FakeAppSettings_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ISettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockISettingsRepository extends _i1.Mock
    implements _i3.ISettingsRepository {
  MockISettingsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.AppSettings> loadSettings() => (super.noSuchMethod(
    Invocation.method(#loadSettings, []),
    returnValue: _i4.Future<_i2.AppSettings>.value(
      _FakeAppSettings_0(this, Invocation.method(#loadSettings, [])),
    ),
  ) as _i4.Future<_i2.AppSettings>);

  @override
  _i4.Future<void> saveSettings(_i2.AppSettings? settings) =>
      (super.noSuchMethod(
        Invocation.method(#saveSettings, [settings]),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [IAppInfoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAppInfoRepository extends _i1.Mock
    implements _i5.IAppInfoRepository {
  MockIAppInfoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> getAppVersion() => (super.noSuchMethod(
    Invocation.method(#getAppVersion, []),
    returnValue: _i4.Future<String>.value(
      _i6.dummyValue<String>(this, Invocation.method(#getAppVersion, [])),
    ),
  ) as _i4.Future<String>);
}
